---
  sensors:
    IRL-FP:
      url: http://fau.loboviz.com/0054.wml
      description: Indian River Lagoon - Fort Pierce
      location:
        lat: 27.475555
        lng: -80.326607
    IRL-LP:
      url: http://fau.loboviz.com/0035.wml
      description: Indian River Lagoon - Link Port
      location:
        lat: 27.534839
        lng: -80.343113
    IRL-SB:
      url: http://fau.loboviz.com/0056.wml
      description: Indian River Lagoon - Sebastian
      location:
        lat: 27.839089
        lng: -80.470822
    IRL-VB:
      url: http://fau.loboviz.com/0055.wml
      description: Indian River Lagoon - Vero Beach
      location:
        lat: 27.590117
        lng: -80.355258
    IRL-JB:
      url: http://fau.loboviz.com/0062.wml
      description: Indian River Lagoon-Jensen Beach
      location:
        lat: 27.224389
        lng: -80.202333
    IRL-SLE:
      url: http://fau.loboviz.com/0061.wml
      description: Indian River Lagoon-St. Lucie Estuary
      location:
        lat: 27.164947
        lng: -80.171844
    SLE-ME:
      url: http://fau.loboviz.com/0060.wml
      description: St. Lucie Estuary-Middle Estuary
      location:
        lat: 27.208928
        lng: -80.247974
    SLE-NF:
      url: http://fau.loboviz.com/0058.wml
      description: St. Lucie Estuary-North Fork
      location:
        lat: 27.210028
        lng: -80.2692
    SLE-SF:
      url: http://fau.loboviz.com/0057.wml
      description: St. Lucie Estuary-South Fork
      location:
        lat: 27.187789
        lng: -80.26418

  measurements:
    temperature:
      medium: water
      unit: C
      name: Temperature
      type: float
    salinity:
      medium: water
      unit: PSU
      name: Salinity
      type: float
    dissolvedOxygen:
      medium: water
      unit: mL/L
      name: Dissolved O2
      type: float
    oxygenSaturation:
      medium: water
      unit: percent
      name: O2 % Saturation
      type: float
    turbidity:
      medium: water
      unit: NTU
      name: Turbidity
      type: float
    cdom:
      medium: water
      unit: QSDE
      name: CDOM
      type: float
    chlorophyll:
      medium: water
      unit: ug/L
      name: Chlorophyll a
      type: float
    nitrate:
      medium: water
      unit: uM
      name: Nitrate
      type: float
    pH:
      medium: water
      unit: pH
      name: pH
      type: float
    phosphate:
      medium: water
      unit: uM
      name: Phosphate
      type: float
    depth:
      medium: water
      unit: m
      name: Depth
      type: float
    currentDirection:
      medium: water
      unit: deg
      name: Current Direction
      type: float
    currentSpeed:
      medium: water
      unit: mm/s
      name: Current Speed
      type: float
    humidity:
      medium: air
      unit: percent
      name: Humidity
      type: float
    par:
      medium: air
      unit: umol/m^2
      name: PAR
      type: float
    barometricPressure:
      medium: air
      unit: inches of Hg
      name: barometric pressure
      type: float
    rain:
      medium: air
      unit: inches/hour
      name: rain
      type: float
    airTemperature:
      medium: air
      unit: F
      name: air temperature
      type: float
    windDirection:
      medium: air
      unit: direction
      name: wind direction
      type: string
    windSpeed:
      medium: air
      unit: mph
      name: wind speed
      type: float
    windGust:
      medium: air
      unit: mph
      name: wind gust
      type: float
